# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TabMenuView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TabMenuView
  
  pod 'Masonry'

  target 'TabMenuViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabMenuViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
